project:
  type: manuscript
  output-dir: _manuscript
  post-render: ./post.sh

manuscript:
  article: paper.md
  notebooks: 
    - notebook: notebooks/representing-orbits.ipynb
      title: Representing Orbits
    - notebook: notebooks/solving-orbits.ipynb
      title: Solving for Orbits
    - notebook: notebooks/manifold-computations.ipynb
      title: Computing Invariant Manifolds
  resources: 
    - "*.bib"
    - "*.ipynb"


format:
  html:
    title-block-style: manuscript
    title-block-banner-color: white
    title-block-banner: "#303446"
    include-in-header: 
      text: <meta theme-color content="#303446"/>
    include-before-body: 
      text: |
        <div class="callout-note callout callout-style-simple">
            <div class="callout-body d-flex">
                <div class="callout-icon-container">
                    <i class="callout-icon"></i>
                    </div>
                    <div class="callout-body-container">
                    <p><i>
                      This page is a <b>pre-print</b>! The published paper is available at 
                      the <a href="https://joss.theoj.org">Journal of Open Source Software</a>.
                    </i></p>
                </div>
            </div>
        </div>

    theme: 
      - _style/light.scss
      - _style/common.scss
      - _style/latte.scss


execute:
  cache: false
  freeze: false
  echo: true
