name: Documentation

on:
  push:
    branches:
      - main
    tags: "*"
  pull_request:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
      - uses: quarto-dev/quarto-actions/setup@v2
      - uses: actions/setup-python@v4
      - run: pip install jupyter

      #
      # AstrodynamicalCalculations Documentation
      #

      - name: Install Documentation Dependencies for AstrodynamicalCalculations
        run: julia --project=lib/AstrodynamicalCalculations/docs -e 'using Pkg; Pkg.develop(PackageSpec(path = joinpath("lib", "AstrodynamicalCalculations"))); Pkg.instantiate(); Pkg.build()'

      - name: Build and deploy AstrodynamicalCalculations
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
        working-directory: lib/AstrodynamicalCalculations
        run: julia --project=docs/ docs/make.jl

      #
      # AstrodynamicalModels Documentation
      #

      - name: Install Documentation Dependencies for AstrodynamicalModels
        run: julia --project=lib/AstrodynamicalModels/docs -e 'using Pkg; Pkg.develop(PackageSpec(path = joinpath("lib", "AstrodynamicalModels"))); Pkg.instantiate(); Pkg.build()'

      - name: Build and deploy AstrodynamicalModels
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
        working-directory: lib/AstrodynamicalModels
        run: julia --project=docs/ docs/make.jl

      #
      # AstrodynamicalSolvers Documentation
      #

      - name: Install Documentation Dependencies for AstrodynamicalSolvers
        run: julia --project=lib/AstrodynamicalSolvers/docs -e 'using Pkg; Pkg.develop(PackageSpec(path = joinpath("lib", "AstrodynamicalSolvers"))); Pkg.instantiate(); Pkg.build()'

      - name: Build and deploy AstrodynamicalSolvers
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
        working-directory: lib/AstrodynamicalSolvers
        run: julia --project=docs/ docs/make.jl

      - name: Install Documentation Dependencies
        run: julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate(); Pkg.build()'


      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # For authentication with GitHub Actions token
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # For authentication with SSH deploy key
        run: julia --project=docs/ docs/make.jl
